export const PERMISSIONS = [
  "chat:use",
  "knowledge:read",
  "knowledge:write",
  "knowledge:review",
  "knowledge:approve",
  "research:run",
  "artifact:generate",
  "prompt:generate",
  "project:read",
  "project:manage",
  "task:read",
  "task:create",
  "task:update",
  "task:complete",
  "task:assign",
  "task:manage",
  "task:notification_manage",
  "organization:manage",
  "member:manage",
  "audit:read",
  "system:diagnose",
  "conversation:read_own",
  "conversation:share",
  "conversation:audit",
  "conversation:audit_manage",
  "clearance:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLES = ["member", "editor", "manager", "admin"] as const;
export type Role = (typeof ROLES)[number];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  member: [
    "chat:use",
    "conversation:read_own",
    "knowledge:read",
    "project:read",
    "task:read",
    "task:create",
    "task:update",
    "task:complete",
  ],
  editor: [
    "chat:use",
    "conversation:read_own",
    "conversation:share",
    "knowledge:read",
    "knowledge:write",
    "research:run",
    "artifact:generate",
    "prompt:generate",
    "project:read",
    "task:read",
    "task:create",
    "task:update",
    "task:complete",
    "task:assign",
  ],
  manager: [
    "chat:use",
    "conversation:read_own",
    "conversation:share",
    "knowledge:read",
    "knowledge:write",
    "knowledge:review",
    "research:run",
    "artifact:generate",
    "prompt:generate",
    "project:read",
    "project:manage",
    "task:read",
    "task:create",
    "task:update",
    "task:complete",
    "task:assign",
    "task:manage",
    "task:notification_manage",
    "member:manage",
    "audit:read",
  ],
  // conversation:audit is intentionally NOT auto-granted with executive clearance.
  // Only admin gets it by default; grant narrowly via membership for real audits.
  admin: [...PERMISSIONS],
};
